INSERT INTO tb_category (name) VALUES ('Books');
INSERT INTO tb_category (name) VALUES ('Electronics');
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name) VALUES ('Books');
INSERT INTO tb_category (name) VALUES ('Electronics');
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name) VALUES ('Books');
INSERT INTO tb_category (name) VALUES ('Electronics');
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name) VALUES ('Books');
INSERT INTO tb_category (name) VALUES ('Electronics');
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name) VALUES ('Books');
INSERT INTO tb_category (name) VALUES ('Electronics');
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name) VALUES ('Books');
INSERT INTO tb_category (name) VALUES ('Electronics');
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name) VALUES ('Books');
INSERT INTO tb_category (name) VALUES ('Electronics');
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name) VALUES ('Books');
INSERT INTO tb_category (name) VALUES ('Electronics');
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name) VALUES ('Books');
INSERT INTO tb_category (name) VALUES ('Electronics');
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name) VALUES ('Books');
INSERT INTO tb_category (name) VALUES ('Electronics');
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name) VALUES ('Books');
INSERT INTO tb_category (name) VALUES ('Electronics');
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name) VALUES ('Books');
INSERT INTO tb_category (name) VALUES ('Electronics');
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name) VALUES ('Books');
INSERT INTO tb_category (name) VALUES ('Electronics');
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());